Nginx in docker
duh2/pet pull request #2
Opened 2021-02-03 09:48 UTC by duh2

2021-02-04 12:58 UTC, Adamovskiy requested changes

2021-02-04 12:58 UTC, Adamovskiy commented on bin/build.sh
> +cd c:/users/duh/IdeaProjects/pet1
Держи чит на получение директории, в которой лежит скрипт:
```bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
```
После этого можно `cd $DIR/..`, или даже `docker build -t mybuild $DIR/..`.

2021-02-04 12:58 UTC, Adamovskiy commented on bin/run.sh
> +docker run -d -p 8080:80 mybuild
Винда определяет исполняемый файл или нет по расширению `.exe`. В Unix-системах за это отвечает мод файла `x`.  Сделай обоим скриптам `chmod a+x` – это даст возможность исполнять файл всем пользователям. Это изменение тоже коммитится. Изменение увидишь в выводе `ls -al`, и после этого сможешь запускать скрипты из консоли. 

PS есть такая особенность: для запуска до скрипта обязательно указывать путь. Даже если он в текущей директории, нужно делать `./run.sh`.

2021-02-04 12:58 UTC, Adamovskiy commented on Dockerfile
> +RUN mv /usr/share/nginx/html/petpage.html /usr/share/nginx/html/index.html
Лучше сделать это переименование прямо в проекте – будет при разработке более явно, что это за файл.

2021-02-04 19:34 UTC, duh2 commented on bin/run.sh
> +docker run -d -p 8080:80 mybuild
А для чего засовывать файлы, создающие образ и докер контейнер в докер контейнер?

2021-02-05 08:20 UTC, Adamovskiy commented on bin/run.sh
> +docker run -d -p 8080:80 mybuild
Нее, ты не понял. В контейнер их засовывать не нужно, в контейнере должно лежать только то, что нужно в рантайме. Эти скрипты – инструменты для тебя, упрощения для разработки. Чтобы вместо того чтобы вспоминать при сборке синтаксис команды docker, просто написать `./build.sh`. А дальше логика сборки будет еще усложняться, будет не одна команда.

Т.е. файлы должны лежать там где лежат, просто в проекте. Проблема в том что они сейчас не исполняемые, а просто текстовые. Тебе нужно у себя на компе локально сделать их исполняемыми, и закоммитить это изменение.

2021-02-05 08:21 UTC, Adamovskiy requested changes
Ответил про исполняемость скриптов.

2021-02-05 13:14 UTC, duh2 commented on bin/run.sh
> +docker run -d -p 8080:80 mybuild
Так они исполняются, только в bash, а не в винде, а относительного того, как это в ней реализовать я хз слегка

2021-02-05 13:15 UTC, duh2 commented on bin/run.sh
> +docker run -d -p 8080:80 mybuild
Если я захожу в директорию и пишу в cmd: build.sh -выполняется скрипт

2021-02-05 14:45 UTC, Adamovskiy approved these changes

2021-02-05 14:45 UTC, merged