Sorting
duh2/pet pull request #4
Opened 2021-02-07 18:24 UTC by duh2

2021-02-08 11:26 UTC, Adamovskiy requested changes

2021-02-08 11:26 UTC, Adamovskiy commented on index.html
> +        <option value="toSmall">по убыванию цены</option>
Для этого обычно используется терминология `asc` (от ascending, по возрастанию) и `desc` (от descending, по убыванию).

2021-02-08 11:26 UTC, Adamovskiy commented on sortprice.js
> +        testToSmall()
Обсудили в личке: это что-то вроде функциональных тестов, а нужны unit.

2021-02-11 13:07 UTC, duh2 commented
Немного накосячил, когда резолвил конфликт, затянул из своего файла еще и изменения по GET request

2021-02-11 17:08 UTC, Adamovskiy requested changes
Здесь все еще присутствуют правки по загрузке с сервера.

2021-02-11 17:08 UTC, Adamovskiy commented on sortprice.js
> +    }
Да, это весьма похоже на баббл-сорт 👍 Осталось доработать, чтобы тесты это подтвердили

2021-02-12 06:47 UTC, duh2 commented on sortprice.js
> +                if (attributes.get('Price') > nextAttributes.get('Price')){
Я пытался обратиться таким образом, но, так как elem не массив - ничего не работало

2021-02-12 06:50 UTC, duh2 commented on sortprice.js
> +  //  xhr.onreadystatechange=readWithCaptiure
это был быстрый откат к sync request, чтоб можно было проверить работу сортировщиков, впредь такого допускать не буду

2021-02-13 14:44 UTC, merged